## OpenCV 기본 연산

### 영상 속성과 화소 접근

#### 실습

In [20]:
import cv2
import numpy as np

imgfile = './data/lena.jpg' # cv2.IMREAD_COLOR 영상으로 img를 읽는다.
img = cv2.imread(imgfile, cv2.IMREAD_COLOR)
# img = cv2.imread(imgfile, cv2.IMREAD_GRAYSCALE)
print('img.ndim = ', img.ndim)
print('img.shape = ', img.shape)
print('img.dtype = ', img.dtype)    # img영상은 img.dim = 3으로 3차원 배열이고,
                                    # img.shape(216, 200, 3)으로 216x200크기의 3채널 영상이다.
                                    # img.shape[0]은 영상의 세로 화소 크기, img.shape[1]은 영상의 가로 화소 크기, img.shape[2]는 영상의 채널 개수이다.
                                    # 각 화소의 자료형은 img.dtype = uint8로 부호없는 8비트 정수이다.

img = img.astype(np.int32)          # 화소자료형을 정수형으로 변경 주요 화소자료형은 np.bool, uint8, np.uint16, np.uint32, np.uint64, np.float32, np.float64,
                                    # np.complex64 등이 있다.
print('img.dtype =', img.dtype)

img = np.uint8(img)                 # 화소 자료형을 uint8로 변경할 수 있다.
print('img.dtype =', img.dtype)     # 영상처리 계산을 위해서 다양한 자료형으로 변결할 필요가 있다. 영상을 표기 하기 위한 cv2.imshow()함수는 uint8 자료형의 영상만을 화면에 표시한다.

img.ndim =  3
img.shape =  (512, 512, 3)
img.dtype =  uint8
img.dtype = int32
img.dtype = uint8


In [28]:
import cv2
import numpy as np

imgfile = './data/lena.jpg' 
img = cv2.imread(imgfile, cv2.IMREAD_GRAYSCALE) # cv2.IMREAD_GRAYSCALE 영상으로 img를 읽는다.
print('img.shape =', img.shape)

# img = img.reshape(img.shape[0] * img.shape[1])
img = img.flatten()                             # 다차원 배열을 1차원 배열로 변경하여 img.shape = (262144,)이다.
print('img.shape =', img.shape)
img = img.reshape(-1, 512, 512)                 # 3차원 배열로 확장한다. -1로 표시된 부분은 크기를 자동으로 계산한다. img의 화소크기가 512x512이므로
                                                # img.shape = (1, 512, 512)로 변경된다.
print('img.shape =', img.shape)

cv2.imshow('img', img[0])                       # 원본 영상을 표시한다. img.reshape()은 실제 데이터를 변경하지 않고, 모양을 변경한다.
cv2.waitKey()
cv2.destroyAllWindows()

img.shape = (512, 512)
img.shape = (262144,)
img.shape = (1, 512, 512)


In [39]:
import cv2
import numpy as np

img = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE) # cv2.IMREAD_GRAYSCALE 영상으로 img를 읽는다.
img[100, 200] = 0                                         # img 영상의 y = 100(행),x = 200(열)화소의 값을 0으로 변경한다. 화소의 인덱스는 y(행),x(열)이다.
print(img[100:110, 200:210])                              # numpy의 슬라이싱으로 y = 100에서 109까지, x = 200에서 209까지의 10x10사각영역을 ROI로 지정하여 출력

for y in range(100, 400):                                 # for문으로 영상의 y = 100에서 399까지, x = 200에서 299까지의 사각영역을 0으로 변경
    for x in range(200, 300):
        img[y, x] = 0

# img[100:400, 200:300] = 0                               # numpy의 슬라이싱으로 ROI를 지정하여 변경할 수 있다. 

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

[[  0 145 143 132 144 141 142 137 137 137]
 [139 135 146 150 139 141 138 142 136 137]
 [129 138 152 139 133 137 139 138 135 131]
 [137 147 139 124 132 141 142 141 130 129]
 [145 140 131 134 142 142 140 131 134 140]
 [144 137 134 147 146 142 129 130 137 137]
 [142 146 141 142 140 139 144 136 133 132]
 [154 142 136 137 144 144 146 135 123 131]
 [144 136 135 133 145 142 129 125 134 138]
 [133 133 144 144 133 130 123 137 140 126]]


In [44]:
import cv2
import numpy as np

img = cv2.imread('./data/lena.jpg', cv2.IMREAD_COLOR) # cv2.IMREAD_GRAYSCALE 영상으로 img를 읽는다.
img[100, 200] = [255, 0, 0]                           # y = 100행, x = 200열의 영상화소 img[100, 200]의 컬러를 리스트 [255, 0, 0] 또는 튜플(255, 0, 0)으로 변경
print(img[100, 200:210])                              # numpy의 슬라이싱으로 y = 100, x = 200에서 209까지의 1x10영역을 ROI로 지정하여 출력

for y in range(100, 400):                             # for문으로 영상의 y = 100에서 399까지, x = 200에서 299까지의 사각영역에 포함된 각 화소를 
    for x in range(200, 300):                         # 파란색[255, 0, 0]으로 변경한다.
        img[y, x] = [255, 0, 0]
        
# img[100:400, 200:300] = [255, 0, 0]                 # numpy의 슬라이싱으로 ROI를 지정하여 변경할 수 있다. 

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

[[255   0   0]
 [109 117 213]
 [113 115 208]
 [114 101 199]
 [121 116 207]
 [105 114 209]
 [112 113 212]
 [107 109 204]
 [117 108 200]
 [110 109 202]]


In [50]:
import cv2
import numpy as np

img = cv2.imread('./data/lena.jpg')

for y in range(100, 400):           # B-채널을 255로 변경
    for x in range(200, 300):
        img[y, x, 0] = 255
        
# img[100:400, 200:300, 0] = 255
img[100:400, 300:400, 1] = 255      # G-채널을 255로 변경
img[100:400, 400:500, 2] = 255      # R-채널을 255로 변경

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

### 관심 영역과 ROI

#### ROI 영역 지정 함수

- cv2.selectROI(windowName, img[, showCrosshair[, fromCenter]]) -> retval

##### windowName 윈도우에 img 영상을 표시하고 사용자가 마우스 클릭과 드래그로 ROI를 선택할 수 있다.
##### showCrosshair = True이면 선택영역에 격자가 표시되고, fromCenter = True이면 마우스 클릭 위치 중심을 기준으로 박스가 선택된다.
##### 선택을 종료하려면 space bar 또는 enter키를 사용하면 반환 값 retval에 선택영역의 튜플(x, y, weight, height)을 반환한다.
##### (x, y)는 박스의 왼쪽-상단 좌표이고, (width, height)는 박스의 가로세로크기이다.
##### c키를 사용하면 선택을 취소하고, (0, 0, 0, 0)을 반환한다.

- cv2.selectROIS(windowName, img[, showCrosshair[, fromCenter]]) -> boundingBoxes

##### windowName 윈도우를 생성에 img 영상에 표시하고, 사용자가 마우스 클릭과 드래그로 다중 ROI를 선택할 수 있다.
##### 마우스 클릭과 드래그로 각 ROI를 선택하고 스페이스바 또는 엔터를 사용하고, 선택영역을 취소하려면 c키를 선택한다.
##### esc키는 다중 ROI 선택을 종료하고, 선택한 영역을 넘파이 배열로 반환한다.

#### 실습

In [6]:
import cv2
import numpy as np

imgfile = './data/lena.jpg' 
src = cv2.imread(imgfile, cv2.IMREAD_GRAYSCALE)
src2 = cv2.imread(imgfile)
dst = np.zeros(src.shape, dtype = src.dtype)
dst2 = np.zeros(src2.shape, dtype = src2.dtype)

# print(dst.shape, dst.dtype)

N = 32
height, width = src.shape
height, width, channel = src2.shape
h = height // N
w = width // N

for i in range(N):
    for j in range(N):
        y = i * h
        x = j * w
        roi = src[y:y + h, x:x + w]
        dst[y:y + h, x:x + w] = cv2.mean(roi)[0]
        dst2[y:y + h, x:x + w] = cv2.mean(roi)[0:3]
        

while True:
    cv2.imshow('dst', dst) 
    cv2.imshow('dst2', dst2)
    key = cv2.waitKey(25)
    if key == 0x1B:
        break
cv2.destroyAllWindows()

In [2]:
import cv2

src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
roi = cv2.selectROI(src)                                  # roi = cv2.selectROI(src)는 디폴트 'ROI select'윈도우에 src영상을 표시하고,
                                                          # 그림에서 마우스클릭과 드래그로 ROI를 선택하고, 스페이스바/엔터키를 누르면 선택한 영역을 roi에 반환한다.
                                                          # 마우스로 ROI를 선택하지 않고 스페이스바/엔터키를 누르면 roi=(0, 0, 0, 0)을 반환한다.
print('roi =',roi)

if roi !=(0, 0, 0, 0):                                    # 선택영역에서 roi[0]은 x열, roi[1]은 y행, roi[2]은 가로크기, roi[3] 세로크기이다.
    img = src[roi[1]:roi[1] + roi[3],
              roi[0]:roi[0] + roi[2]]
    cv2.imshow('img',img)                                 # img = src[roi[1]:roi[1] + roi[3], roi[0]:roi[0] + roi[2]]는 src에서 선택영역의 roi를 img에 저장한다.
    cv2.waitKey()
cv2.destroyAllWindows()

roi = (205, 206, 148, 178)


In [3]:
import cv2

src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
rects = cv2.selectROIs('src', src, False, True)            # 'src' 윈도우에 src영상을 표시하고, showCrosshair = False로 선택영역에 격자를 표시하지 않고
                                                           # fromCenter = True로 마우스 클릭 위치 중심을 기준으로 드래그하여 박스를 선택하고,
                                                           # 스페이스바/엔터키를 눌러 반복적으로 ROI영역을 지정하고, Esc키를 눌러 다중 영역 선택을 종료하면
                                                           # rects에 반환한다.
print('rect =', rects)

for r in rects:
    cv2.rectangle(src, (r[0], r[1]),
                  (r[0] + r[2], r[1] + r[3]), 255)         # 선택된 다중 영역의 리스트의 각각의 ROI영역 r을 이용하여 src 영상에 사각형을 그려 표시한다.
    # img = src[r1[1]:r[1] + r[3], r[0]:r[0] + r[2]]
    # cv2.imshow('img', img)
    # cv2.waitKey()
cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

rect = ()


### 영상 복사

#### 실습

In [2]:
import cv2

src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

# dst = src               # 참조
dst = src.copy()          # 복사
dst[100:400, 200:300] = 0 # copy()를 안쓰고 참조를쓰면 src파일까지 변경된다.

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
import cv2
src = cv2.imread('./data/lena.jpg')

dst = cv2.split(src) # 3-채널 BGR 컬러영상 src를 채널 분리하여 튜플 dst에 저장한다.
print(type(dst))
print(type(dst[0])) # type(dst[1]), type(dst[2])

cv2.imshow('blue',  dst[0])
cv2.imshow('green', dst[1])
cv2.imshow('red',   dst[2])
cv2.waitKey()    
cv2.destroyAllWindows()


<class 'tuple'>
<class 'numpy.ndarray'>


### 영상 채널 분리 및 병합

#### 실습

In [7]:
# 0411.py
import cv2
src = cv2.imread('./data/lena.jpg')

dst = cv2.split(src)                              # 3-채널 컬러 영상 src를 채널 분리하여 튜플 sdt에 저장한다.
print(type(dst))
print(type(dst[0])) # type(dst[1]), type(dst[2])

cv2.imshow('src', src)
cv2.imshow('blue',  dst[0])
cv2.imshow('green', dst[1])
cv2.imshow('red',   dst[2])
cv2.waitKey()    
cv2.destroyAllWindows()


<class 'tuple'>
<class 'numpy.ndarray'>


In [11]:
# 0412.py
import cv2
src = cv2.imread('./data/lena.jpg')

b, g, r = cv2.split(src)            # 3-채널 컬러 영상 src를 채널 분리하여 b, g, r에 저장한다.
dst = cv2.merge([b, g, r])          # 리스트[b, g, r]을 dst에 채널 합성한다. 리스트의 항목의 순서 b, g, r의 순서는 채널 순서로 중요하다.
                                    # cv2.merge([r, g, b])는 다른 색상의 컬러 영상을 생성한다.
# dst = cv2.merge([r, g, b])


print(type(dst))
print(dst.shape)
cv2.imshow('src', src)
cv2.imshow('dst',  dst)
cv2.waitKey()    
cv2.destroyAllWindows()


<class 'numpy.ndarray'>
(512, 512, 3)


### 컬러 공간 변환

- cv2.cvtColor(src, code[, dst[, dsdtCn ]])

##### 입력 영상 src를 code에 따라 출력 영상 dst에 반환한다.
##### dstCn은 출력 영상의 채널 수이다.
##### 컬러 변환에서 R, G, B 채널의 값은 영상의 자료형에 따라 np.uing8은 0..255, np.uint16은 0..65535, np.float32는 0..1의 범위로 간주한다.
##### 선형변환의 경우 화소 자료형을 따르는 값의 범위가 문제 되지 않지만, 비선형 변환의 경우 문제가 될 수 있다.
##### 그러므로 컬러 변환 전에 astype()함수를 사용하여 np.uint16, np.uint32 또는 np.float32로 변환할 필요가 있을 수 있다.

#### 실습

In [13]:
# 0413.py
import cv2
src = cv2.imread('./data/lena.jpg')

gray   = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
yCrCv = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)
hsv    = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)

cv2.imshow('gray',  gray)
cv2.imshow('yCrCv', yCrCv)
cv2.imshow('hsv',   hsv)

cv2.waitKey()    
cv2.destroyAllWindows()

### 영상의 크기 변환과 회전

- cv2.resize(src, dsize[, dst[, fx[, fy[, interpolation ]]]])

##### 입력 영상을 크기 변환하여 반환한다.
##### src는 입력 영상, dsize는 출력 영상의 크기, dst는 출력 영상, fx, fy는 가로와 세로의 스케일이고, interpolation cv2.INTER_NEAREST, cv2.INTER_LINEAR, cv2.INTER_AREA, cv2.INTER_CUBIC, cv2.INTER_LANCZOS4 등의 보간법이다. 출력 영상 dst를 반환한다.

- cv2.rotate(src, rotateCode[, dst])

##### 입력 영상 src를 크기 rotateCode에 따라 90의 배수로 회전시켜 dst에 반환한다.
##### rotateCode는 cv2.ROTATE_90_CLOCKWISE, cv2.ROTATE_180, cv2.ROTATE_90_COUNTERCLOCKWISE 등이 있다

- cv2.getRotationMatrix2D(center, angle, scale)

##### center 좌표를 중심으로 scale 확대/축소하고, angle 각도만큼 회전한 어파인 변환행렬 M을 반환한다.
##### angle > 0이면 반시계방향 회전이다. M[:, 2] += (tx, ty)를 추가하면 이동을 추가할 수 있다.

- cv2.warpAffine(src, M, dsize[, dst[, flags[, borderMode[, borderValue ]]]])

##### cv2.warpAffine() 함수는 src 영상에 2x3 어파인 변환행렬 M을 적용하여 dst에 반환한다.
##### dsize는 출력 영상 dst의 크기이며, flags는 보간법(cv2.INTER_NEARREST, cv2.INTER_LINEAR 등)과 cv2.WARP_INVERSE_MAP의 조합니다.
##### cv2.WARP_INVERSE_MAP은 M이 dst ->의 역변환을 의미한다.
##### borderMode는 경계값 처리방식이다.
##### borderMode = cv2.BORDER_CONSTANT에서 borderValue는 경계값 상수이다.

#### 실습

In [3]:
# 0414.py
import cv2
import numpy as np
src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

dst = cv2.resize(src, dsize=(320, 240))                    # src를 가로 320, 세로 240 크기로 변환하여 dst에 저장한다. dst.shape은 (240, 320)이다.
dst2 = cv2.resize(src, dsize=(0,0), fx=1.5, fy=1.2)        # dst2 = cv2.resize(src, dsize = (0, 0), fx = 1.5, fy = 1.2)는 src를 가로 fx = 1.5배, 세로 fy = 1.2배로 변환하여 dst2에 저장한다.

cv2.imshow('dst', dst)
cv2.imshow('dst2', dst2)
cv2.waitKey()    
cv2.destroyAllWindows()


In [6]:
# 0415.py
import cv2
src = cv2.imread('./data/lena.jpg')

dst1 = cv2.rotate(src, cv2.ROTATE_90_CLOCKWISE)         # 시계방향으로 90도 회전
dst2 = cv2.rotate(src, cv2.ROTATE_90_COUNTERCLOCKWISE)  # 반시계방향으로 90도 회전

cv2.imshow('dst1',  dst1)
cv2.imshow('dst2',  dst2)
cv2.waitKey()    
cv2.destroyAllWindows()

In [12]:
# 0416.py
import cv2
src = cv2.imread('./data/lena.jpg')

rows, cols, channels = src.shape
print(src.shape)
M1 = cv2.getRotationMatrix2D( (rows/2, cols/2),  45, 0.5 ) # 영상의 중심인 center = (rows/2, cols/2)를 기준으로 scale = 0.5로 축소하고,
                                                           # angle = 45도로 반시계방향으로 회전한 어파인 변환행렬 M1을 생성한다.
M2 = cv2.getRotationMatrix2D( (rows/2, cols/2), -45, 1.0 ) # 영상의 중심인 center = (rows/2, cols/2)를 기준으로 scale = 1로 확대나 축소하지 않고,
                                                           # angle = -45도로 시계방향으로 회전한 어파인 변환행렬 M2를 생성한다.

dst1 = cv2.warpAffine( src, M1, (rows, cols))              # src 영상에 2x3 어파인 변환행렬 M1을 적용하여 (rows, cols)의 크기의 dst1영상을 생성한다.
dst2 = cv2.warpAffine( src, M2, (rows, cols))              # src 영상에 2x3 어파인 변환행렬 M2을 적용하여 (rows, cols)의 크기의 dst1영상을 생성한다.

cv2.imshow('dst1',  dst1)
cv2.imshow('dst2',  dst2)
cv2.waitKey()    
cv2.destroyAllWindows()

(512, 512, 3)


### 산술연산ㆍ비트연산ㆍ비교범위ㆍ수치연산 함수

##### 연산결과가 자료형의 범위를 벗어나는 경우 주의해서 사용한다

#### 실습

In [42]:
## 영상 덧셈
# 0417.py
import cv2
import numpy as np

src1 = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
src2 = np.zeros(shape=(512,512), dtype=np.uint8) + 100

dst1 = src1 + src2                                          # numpy의 배열 덧셈으로 결과가 255를 넘는 경우, 256으로 나눈 나머지를 계산한다.
dst2 = cv2.add(src1, src2)                                  # cv2.add()함수로 덧셈하여 결과가 255를 넘는 경우, 255로 계산한다.
# dst2 = cv2.add(src1, src2, dtype = cv2.CV_8U)             # numpy자료형을 dtype을 cv2.CV_8U와 같이 opencv 자료형으로 명시 가능

cv2.imshow('dst1',  dst1)
cv2.imshow('dst2',  dst2)
cv2.waitKey()    
cv2.destroyAllWindows()


In [44]:
## 비트연산
# 0418.py: OpenCV-Python Tutorials 참조
import cv2
import numpy as np

src1 = cv2.imread('./data/lena.jpg')
src2 = cv2.imread('./data/opencv_logo.png')
cv2.imshow('src2',  src2)

#1
rows,cols,channels = src2.shape
roi = src1[0:rows, 0:cols]                                    # 전체 크기에 대한 src1의 영역을 roi에 저장

#2
gray = cv2.cvtColor(src2,cv2.COLOR_BGR2GRAY)                  # 컬러영상을 그레이스케일 영상 gray로 변환
ret, mask = cv2.threshold(gray, 160, 255, cv2.THRESH_BINARY)  # 전경과 배경을 구분하기 위해 이미지 대상 gray, 임계값 160,
                                                              # 임계값을 넘었을 때 적용할 value 255, type = binary로 이진 영상 mask 생성
mask_inv = cv2.bitwise_not(mask)                              # 비트 반전 영상 mask_inv 생성
cv2.imshow('mask',  mask)
cv2.imshow('mask_inv',  mask_inv)

#3
src1_bg = cv2.bitwise_and(roi, roi, mask = mask)              # roi 영상에서 mask의 255인 화소만 bitwise_and() 함수로 src1의 배경영역 복사
                                                              # 전경영역은 0인 src1_bg 생성
cv2.imshow('src1_bg',  src1_bg)

#4
src2_fg = cv2.bitwise_and(src2, src2, mask = mask_inv)        # cv2.bitwise_and() 함수로 mask_inv 마스크를 사용하여 src2에서 전경영역을 src2_fg에 복사
cv2.imshow('src2_fg',  src2_fg)

#5
## dst = cv2.add(src1_bg, src2_fg)
dst = cv2.bitwise_or(src1_bg, src2_fg)                        # cv2.bitwise_or() 함수로 src_bg와 src2_fg를 비트 OR 연산하여 dst를 생성, add()함수 사용해도 동일
cv2.imshow('dst',  dst)

#6
src1[0:rows, 0:cols] = dst                                    # dst를 src1에 복사하여 'result' 영상에 생성

cv2.imshow('result',src1)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [46]:
## 반전 영상
# 0419.py
import cv2
import numpy as np

src1 = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)
src2 = np.zeros(shape=(512,512), dtype=np.uint8) + 255

dst1 = 255 - src1                                          # numpy의 브로드 캐스팅으로 255를 src1를 src1 크기의 배열로 확장하고, src1의 각 화소와 뺄셈으로 계산하고 src1 영상의 값을 반전영상 dst1을 생성
dst2 = cv2.subtract(src2, src1)                            # cv2.subtract() 함수를 사용하여 (src2 - src1) 연산으로 src1의 화소값을 반전
dst3 = cv2.compare(dst1, dst2, cv2.CMP_NE)                 # dst1과 dst2의 각 화소를 cv2.CMP_NE(not equal to) 비교하여, 참이면 255, 거짓이면 0을 dst 영상의 각 화소에 출력한다.
                                                           # dst1과 dst2는 모든 화소에서 같은 값을 가진다.
                                                           # cv2.compare()함수는 cv2.CMP_EQ, cv2.CMP_NE, cv2.CMP_GT, cv2.CMP_LT, cv2.CMP_LE 등의 비교를 할 수 있다.
n    = cv2.countNonZero(dst3)                              # 0이 아닌 화소를 카운트하여 반환한다. dst3의 화소는 모두 0이기에 n은 0이다.
print('n = ', n)
cv2.imshow('src1', src1)
cv2.imshow('src2', src2)
cv2.imshow('dst1',  dst1)
cv2.imshow('dst2',  dst2)
cv2.waitKey()    
cv2.destroyAllWindows()


n =  0


In [47]:
## cv2.normalize()에 의한 영상 정규화
# 0420.py
import cv2
import numpy as np

src = cv2.imread('./data/lena.jpg', cv2.IMREAD_GRAYSCALE)

minVal, maxVal, minLoc, maxLoc = cv2.minMaxLoc(src)        # cv2.minMaxLoc(src)는 src의 최소값, 최대값, 최소값 위치, 최대값 위지를 계산하여 반환한다.
                                                           # 최소/최대값이 여러 개인 경우, 최초의 값의 위치를 반환한다.
print('src:', minVal, maxVal, minLoc, maxLoc)

dst = cv2.normalize(src, None, 100, 200, cv2.NORM_MINMAX)  # cv2.normalize()는 norm_type = cv2.NORM_MINMAX에 의해 src의 최소/최대값 범위를 [100, 200]으로 정규화한다.
                                                           # dst = None은 결과 영상을 새로 생성한다.
minVal, maxVal, minLoc, maxLoc = cv2.minMaxLoc(dst)
print('dst:', minVal, maxVal, minLoc, maxLoc)

cv2.imshow('dst',  dst)
cv2.waitKey()    
cv2.destroyAllWindows()


src: 18.0 248.0 (265, 198) (116, 273)
dst: 100.0 200.0 (265, 198) (116, 273)


In [5]:
## cv2.randu()에 2차원 균등분포 난수 좌표
# 0421.py
import cv2
import numpy as np
import time

dst = np.full((512,512,3), (255, 255, 255), dtype= np.uint8)     # 512x512x3 배열에 255를 부호없는 정수로 꽉채운다.
nPoints = 100
pts = np.zeros((1, nPoints, 2), dtype=np.uint16)
cv2.setRNGSeed(int(time.time()))                                 # cv2.setRNGSeed(int(time.time()))는 난수 생성을 초기화한다.
                                                                 # 초기화하지 않으면 항상 같은 난수열을 생성하므로 주의한다.
                                                                 # 3차원 튜플형식의 배열이고 2차원안에 100개가 들어간다. 1x100x2
    
cv2.randu(pts, (0, 0), (512, 512))                               # 1 x nPoint이고 2-채널인 pts 배열에 (0, 0)에서 (512, 512) 범위의 균등분포 난수를 생성한다.
            
# draw points
for k in range(nPoints):                                         
    x, y = pts[0, k][:] # pts[0, k, :]                           # ptspts[0, k]의 채널데이터를 x, y에 저장한다. 0부터 k 까지의 배열 요소 중 처음부터 끝까지를 x와 y에 저장
    cv2.circle(dst,(x,y),radius=5,color=(0,0,255),thickness=-1)  # 좌표x,y에 반지름이 5, color = (0, 0, 255)인 원을 dst에 넣는다 두께를 -1로하면 내부가 채워짐
    
    
cv2.imshow('dst',  dst)
cv2.waitKey()    
cv2.destroyAllWindows()


In [15]:
## cv2.randn()에 2차원 정규분포 난수 좌표
# 0422.py
import cv2
import numpy as np
import time

dst = np.full((512,512,3), (255, 255, 255), dtype= np.uint8)
nPoints = 100
pts = np.zeros((1, nPoints, 2), dtype=np.uint16)

cv2.setRNGSeed(int(time.time()))                                 # 난수 생성을 초기화한다. 초기화하지 않으면 항상 같은 난수열을 생성한다.
cv2.randn(pts, mean=(256, 256), stddev=(50, 50))                 # cv2.randn()함수로 1xnPoints이고 2-채널인 pts 배열에 평균이(256, 256), 편차가(50, 50)인 정규 분포 난수를 생성한다.
            
# draw points
for k in range(nPoints):
    x, y = pts[0][k, :] # pts[0, k, :]                           # ptspts[0, k]의 채널 데이터를 x, y에 저장한다.
    cv2.circle(dst,(x,y),radius=5,color=(0,0,255),thickness=-1)  # cv2.circle() 함수로 좌표(x, y)에 반지름 radius = 5, red색상이고 내부를 채운 원을 그린다.
    
cv2.imshow('dst', dst)                
cv2.waitKey()    
cv2.destroyAllWindows()


In [21]:
## cv2.Mahalanobis()에 의한 통계적 거리 계산
# 0423.py
import cv2
import numpy as np

X = np.array([[0, 0,  0, 100, 100, 150, -100, -150],
              [0, 50, -50, 0, 30, 100, -20, -100]], dtype=np.float64)      # 62비트 실수형의 2차원 배열 생성

X = X.transpose() # X = X.T                                                # 전치행렬로 변경하여, 각 행의 요소가 열로 열의 요소가 행으로 바뀌는 2차원 좌표로 위치시킨다.

cov, mean = cv2.calcCovarMatrix(X, mean=None, 
                               flags = cv2.COVAR_NORMAL + cv2.COVAR_ROWS)  # cv2.calcCovarMatrix(X, mX, cv2.COVAR_NORMAL + cv2.COVAR_ROWS)는
                                                                           # input인 X의 각 행(cv2.COVAR_ROWS)에서 (x, y) 좌표의 평균 mean, 공분산 행렬 cov를 계산한다.
                                                                           # 평균 mean은 1x2 열벡터이고, 공분산 행렬 cov는 2x2 행렬이다.
                                                                           # 만약 데이터가 행렬의 열에 있으면 flags에 cv2.COVAR_COLS를 사용한다.
print('mean=', mean)
print('cov=', cov)

ret, icov = cv2.invert(cov)                                                # ret, icov = cv2.invert(cov)는 공분산 행렬 cov의 역행렬 icov를 계산한다.
print('icov=',icov)

v1 = np.array([[0],[0]] , dtype=np.float64)
v2 = np.array([[0],[50]], dtype=np.float64)

dist = cv2.Mahalanobis(v1, v2, icov)                                       # dist = cv2.Mahalanobis(v1, v2, icov)는 두 벡터 v1, v2 사이의 통계적 거리인 마하라노비스 거리로 공분산 행렬의 역행렬을 이용하여 계산한다.
print('dist = ', dist)
                
cv2.waitKey()    
cv2.destroyAllWindows()


mean= [[12.5   1.25]]
cov= [[73750.  34875. ]
 [34875.  26287.5]]
icov= [[ 3.63872307e-05 -4.82740722e-05]
 [-4.82740722e-05  1.02084955e-04]]
dist =  0.5051854992128457


In [1]:
# 0424.py
import cv2
import numpy as np
 
X = np.array([[0, 0,  0,100,100,150, -100,-150],
                 [0,50,-50,  0, 30,100,  -20,-100]], dtype=np.float64)     # 64비트 실수형인 2차원 배열 생성
X = X.transpose() # X = X.T                                                # 행렬 전치

cov, mean = cv2.calcCovarMatrix(X, mean=None,
                                    flags=cv2.COVAR_NORMAL+cv2.COVAR_ROWS) # # cv2.calcCovarMatrix(X, mX, cv2.COVAR_NORMAL + cv2.COVAR_ROWS)는
                                                                           # input인 X의 각 행(cv2.COVAR_ROWS)에서 (x, y) 좌표의 평균 mean, 공분산 행렬 cov를 계산한다.
                                                                           # 평균 mean은 1x2 열벡터이고, 공분산 행렬 cov는 2x2 행렬이다.
                                                                           # 만약 데이터가 행렬의 열에 있으면 flags에 cv2.COVAR_COLS를 사용한다.
            
ret, icov = cv2.invert(cov)                                                # ret, icov = cv2.invert(cov)는 공분산 행렬 cov의 역행렬 icov를 계산한다.

dst = np.full((512,512,3), (255, 255, 255), dtype= np.uint8)
rows, cols, channel = dst.shape
centerX = cols//2                                                          # 256
centerY = rows//2                                                          # 256

v2 = np.zeros((1,2), dtype=np.float64)                                     # 배열의 요소가 0이고 64비트 실수형 타입의 (1,2)2차원 튜플 생성
FLIP_Y = lambda y: rows - 1 - y                                            # FLIP_Y(y)함수는 y 좌표를 rows -1 -y로 변환하여 y-축을 반전시킨다.

# draw Mahalanobis distance
for y in range(rows):
    for x in range(cols):
        v2[0,0] = x - centerX
        v2[0,1] = FLIP_Y(y) - centerY # y-축 뒤집기 
        dist = cv2.Mahalanobis(mean, v2, icov)                             # dist =cv2.Mahalanobis(mean, v2, icov)는 rows x cols의 각 좌표를 중심점 (centerX, centerY)을 원점으로 변환한 벡터 v2와 평균 벡터 mean의 마하라노비스 거리 dist를 계산한다.
        
        if dist < 0.1:                                                     # dist < 0.1이면 [50, 50, 50], dist < 0.3이면 [100, 100, 100], dist < 0.8이면 [200, 200, 200], 그 외에는 [250, 250, 250] 색상을 dst[y,x]에 저장한다.
            dst[y, x] = [50, 50, 50]
        elif dist < 0.3:
            dst[y, x] = [100, 100, 100]
        elif dist < 0.8:
            dst[y, x] = [200, 200, 200]
        else:
            dst[y, x] = [250, 250, 250]
            
for k in range(X.shape[0]):                                                # X의 k-번째 행의 좌표를 (x, y)를 원점(centerX, centerY)를 기준으로 좌표(cx, cy)로 변환하고,
    x, y = X[k,:]                                                          # cy = FLIP_Y(cy)로 y-좌표를 반전시켜 cv2.circle()함수로 dst에 빨간색(0, 0, 255) 원으로 표시된다.
    cx = int(x+centerX)
    cy = int(y+centerY)
    cy = FLIP_Y(cy)
    cv2.circle(dst,(cx,cy),radius=5,color=(0,0,255),thickness=-1)
    
# draw X, Y-axes
cv2.line(dst, (0, 256), (cols-1, 256), (0, 0, 0))
cv2.line(dst, (256,0), (256,rows), (0, 0, 0))

# calculate eigen vectors
ret, eVals, eVects = cv2.eigen(cov)                                        # ret, eVals, evects = cv2.eigen(cov)는 공분산 행렬 cov의 고유값 eVals, 고유 벡터 eVects를 계산한다.
print('eVals=',  eVals)
print('eVects=', eVects)

def ptsEigenVector(eVal, eVect):                                           # def ptsEigenVector(eVal, eVect)는 고유값 eVal, 고유벡터 eVect를 이용하여
                                                                           # 고유 벡터위의 대칭인 두 좌표(x1, y1), (x2, y2)을 계산한다.
##    global mX, centerX, centerY                                          # scale = np.sqrt(eVal)은 고유값의 제곱근을 scale에 저장한다.
                                                                           # x1 = scale * eVect[0], y1 = scale * eVect[1]은 고유 벡터를 scale하여
    scale = np.sqrt(eVal) # eVal[0]                                        # 좌표 (x1, y1)를 계산하고, x2, y2 = -x1, -y1은 대칭을 이용하여
    x1 = scale*eVect[0]                                                    # (x2, y2)를 계산한다.
    y1 = scale*eVect[1]                                                    # 좌표(x1, y1), (x2, y2)을 평균벡터로 이동하고, 
    x2, y2 = -x1, -y1 # 대칭                                                
    x1 += mean[0,0] + centerX                                              # 원점을 (centerX, centerY)로 변환하고, y1, y2는 반전시킨다.
    y1 += mean[0,1] + centerY
    x2 += mean[0,0] + centerX
    y2 += mean[0,1] + centerY
    y1 = FLIP_Y(y1)
    y2 = FLIP_Y(y2)
    return int(x1), int(y1), int(x2), int(y2)

 
# draw eVects[0]
x1, y1, x2, y2 = ptsEigenVector(eVals[0], eVects[0])                       # x1, y1, x2, y2 = ptsEigenVector(eVals[0], eVects[0])는 고유값 eVals[0],
cv2.line(dst, (x1, y1), (x2, y2), (255, 0, 0), 2)                          # 고유 벡터 eVects[0]을 이용하여 고유 벡터 위의 대칭인 두 좌표(x1, y1), (x2, y2)을 계산한다.
                                                                           # cv2.line(dst, (x1, y1), (x2, y2), (255, 0, 0), 2)으로 dst에 파란색(255, 0, 0)라인으로 그린다.
# draw eVects[1]
x1, y1, x2, y2 = ptsEigenVector(eVals[1], eVects[1])
cv2.line(dst, (x1, y1), (x2, y2), (255, 0, 0), 2)

cv2.imshow('dst', dst)               
cv2.waitKey()    
cv2.destroyAllWindows()


eVals= [[92202.13359547]
 [ 7835.36640453]]
eVects= [[ 0.88390424  0.46766793]
 [-0.46766793  0.88390424]]


In [4]:
# 0425.py
import cv2
import numpy as np

X = np.array([[0, 0,  0,100,100,150, -100,-150],
                 [0,50,-50,  0, 30,100,  -20,-100]], dtype=np.float64)
X = X.transpose() # X = X.T

##mean = cv2.reduce(X, 0, cv2.REDUCE_AVG)
##print('mean = ', mean)

mean, eVects = cv2.PCACompute(X, mean=None)  # X의 평균 벡터 mean, 공분산 행렬의 고유 벡터 eVects를 계산한다.
print('mean = ', mean)
print('eVects = ', eVects)

Y =cv2.PCAProject(X, mean, eVects)           # 고유 벡터 eVects에 의해 PCA 두영한다. 즉 데이터를 고유 벡터를 축으로 한 좌표로 변환한다.
print('Y = ', Y)

X2 =cv2.PCABackProject(Y, mean, eVects)      # Y를 PCA 역투영하면 원본 X를 복구할 수 있다. X와 X2는 오차범위 내에서 같은 값을 갖는다. 즉, np.alllose(X, X2)는 True이다.
print('X2 = ', X2)
print(np.allclose(X, X2))
cv2.waitKey()    
cv2.destroyAllWindows()


mean =  [[12.5   1.25]]
eVects =  [[ 0.88390424  0.46766793]
 [-0.46766793  0.88390424]]
Y =  [[ -11.63338792    4.74096885]
 [  11.75000868   48.93618085]
 [ -35.01678451  -39.45424315]
 [  76.75703609  -42.02582434]
 [  90.78707404  -15.50869713]
 [ 167.71904127   22.98120308]
 [-109.37717055   33.82967723]
 [-190.9858171   -13.49926538]]
X2 =  [[ 1.77635684e-15  0.00000000e+00]
 [ 3.55271368e-15  5.00000000e+01]
 [ 0.00000000e+00 -5.00000000e+01]
 [ 1.00000000e+02 -7.10542736e-15]
 [ 1.00000000e+02  3.00000000e+01]
 [ 1.50000000e+02  1.00000000e+02]
 [-1.00000000e+02 -2.00000000e+01]
 [-1.50000000e+02 -1.00000000e+02]]
True


In [7]:
# 0426.py
import cv2
import numpy as np

src = cv2.imread('./data/lena.jpg') 
b, g, r = cv2.split(src)                                          # 'lena.jpg'영상을 컬러로 읽은 src를 b, g, r로 채널을 분리한다.
cv2.imshow('b', b)
cv2.imshow('g', g)
cv2.imshow('r', r)

X = src.reshape(-1, 3)                                            # 행값에 -1이들어가면 3열로된 2차원배열로 행은 자동으로 맞춰서 생성이 된다. 
print('X.shape=', X.shape)

mean, eVects = cv2.PCACompute(X, mean=None)                       # X의 평균 벡터 mean, 공분산 행렬의 고유벡터 eVects를 계산한다. eVect는 3x3행렬이다.
print('mean = ', mean)
print('eVects = ', eVects)

Y =cv2.PCAProject(X, mean, eVects)                                # 고유 벡터 eVects에 의해 X를 Y에 PCA 투영한다.
Y = Y.reshape(src.shape)                                          # Y의 모양을 재조정한다. Y.shape = (512, 512, 3)
print('Y.shape=', Y.shape)

eImage = list(cv2.split(Y))                                       # Y를 elmage에 채널 분리
for i in range(3): 
    cv2.normalize(eImage[i], eImage[i], 0, 255, cv2.NORM_MINMAX)  # 각 채널 elmage[i]의 값을 [0, 255]로 정규화
    eImage[i]=eImage[i].astype(np.uint8)                          # 8-비트 영상으로 변환한다.
    
cv2.imshow('eImage[0]', eImage[0])
cv2.imshow('eImage[1]', eImage[1])
cv2.imshow('eImage[2]', eImage[2])
cv2.waitKey()    
cv2.destroyAllWindows()


X.shape= (262144, 3)
mean =  [[105.39899  99.5627  179.7303 ]]
eVects =  [[ 0.3958077   0.68919426  0.6069166 ]
 [-0.6352216  -0.27180612  0.72292113]
 [ 0.6631967  -0.6716642   0.3302081 ]]
Y.shape= (512, 512, 3)
